//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TEC_QA_CRMEntities : DbContext
    {
        public TEC_QA_CRMEntities()
            : base("name=TEC_QA_CRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CorporateRepresentative> CorporateRepresentatives { get; set; }
        public virtual DbSet<Corporation> Corporations { get; set; }
        public virtual DbSet<CorporationsPhoneNumber> CorporationsPhoneNumbers { get; set; }
        public virtual DbSet<ErrorReport> ErrorReports { get; set; }
        public virtual DbSet<Person> Persons { get; set; }
        public virtual DbSet<PersonsPhoneNumber> PersonsPhoneNumbers { get; set; }
        public virtual DbSet<ReviewPetition> ReviewPetitions { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<SalesPetition> SalesPetitions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersSession> UsersSessions { get; set; }
        public virtual DbSet<Contact_View> Contact_View { get; set; }
        public virtual DbSet<Training> Trainings { get; set; }
        public virtual DbSet<UserXTraining> UserXTrainings { get; set; }
    
        public virtual ObjectResult<getTrainings_Result> getTrainings(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getTrainings_Result>("getTrainings", userIDParameter);
        }
    
        public virtual ObjectResult<getRelationatedProducts_Result> getRelationatedProducts(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getRelationatedProducts_Result>("getRelationatedProducts", userIDParameter);
        }
    
        public virtual int sp_Insert_Error_Report(Nullable<int> userID, Nullable<int> saleID, string product, Nullable<System.DateTime> errorDate, string email, string descrition)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var saleIDParameter = saleID.HasValue ?
                new ObjectParameter("SaleID", saleID) :
                new ObjectParameter("SaleID", typeof(int));
    
            var productParameter = product != null ?
                new ObjectParameter("Product", product) :
                new ObjectParameter("Product", typeof(string));
    
            var errorDateParameter = errorDate.HasValue ?
                new ObjectParameter("ErrorDate", errorDate) :
                new ObjectParameter("ErrorDate", typeof(System.DateTime));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var descritionParameter = descrition != null ?
                new ObjectParameter("Descrition", descrition) :
                new ObjectParameter("Descrition", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_Error_Report", userIDParameter, saleIDParameter, productParameter, errorDateParameter, emailParameter, descritionParameter);
        }
    }
}
