//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorReport
    {
        public string errorMessage;

        public int ErrorID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> SaleID { get; set; }
        public string ProductName { get; set; }
        public Nullable<System.DateTime> ErrorDate { get; set; }
        public string ContactMail { get; set; }
        public string ErrorDescription { get; set; }
    
        public virtual Sale Sale { get; set; }
        public virtual User User { get; set; }
    }
}
