//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewPetition
    {
        public int PetitionID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public System.DateTime ReviewDate { get; set; }
        public Nullable<int> SaleID { get; set; }
        public Nullable<bool> State { get; set; }
        public string Observations { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual SalesPetition SalesPetition { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
