//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewPetition
    {
        public int PetitionID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public System.DateTime ReviewDate { get; set; }
        public Nullable<int> SaleID { get; set; }
        public Nullable<bool> State { get; set; }
        public string Observations { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual SalesPetition SalesPetition { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
