//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesPetition
    {
        public int PetitionID { get; set; }
        public int ClientID { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public decimal Cost { get; set; }
    
        public virtual ReviewPetition ReviewPetition { get; set; }
        public virtual User User { get; set; }
    }
}
