//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserXTraining
    {
        public int userXTrainingID { get; set; }
        public int fUserID { get; set; }
        public int fTrainingID { get; set; }
        public string trainingState { get; set; }
        public Nullable<int> calification { get; set; }
    
        public virtual Training Training { get; set; }
        public virtual User User { get; set; }
    }
}
