//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersSession
    {
        public int SessionID { get; set; }
        public Nullable<int> UserID { get; set; }
        public bool ActiveSession { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime FinishDate { get; set; }
        public byte[] SessionIP { get; set; }
    
        public virtual User User { get; set; }
    }
}
